@baseUrl = http://localhost:3333

# @name create_account
POST {{baseUrl}}/accounts
Content-Type: application/json


{
  "name": "Daniel Harrison",
  "email": "daniel@example.com",
  "password": "123456"
}

###

# @name authenticate
POST {{baseUrl}}/accounts
Content-Type: application/json


{
  "name": "Daniel Harrison",
  "email": "daniel@example.com",
  "password": "123456"
}